# Generated by Django 4.2.13 on 2024-06-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank='True', max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank='True', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
